### ISSUE TITLE
Win32 VS2013 "libopencc" Project error

### ISSUE THREAD

**Issue by SONIC3D** [BYVoid/OpenCC#131]
After running CMake with the parameters provided in readme file,the generated project of "libopencc" contains the following errors in all build profiles:

1.In Project Properties->General,the TargetName is started with install prefix string which is expected to be "opencc" only.

2.In Project Properties->Linker->Debugging,the "Generate Program Database File" constains wrong file path that combined two absolute dirs in one path.That will cause build error for the directory cannot be created.

3.The install process will copy .lib file of this project only.If it is built in dynamic library form(which is default option after running CMake).The .dll file will not be copied to <install prefix>/bin dir.

**Comment by EchterAgo** [comment]
I think the first two problems are caused by these lines in the main CMakeLists.txt:

if (WIN32)
  set(CMAKE_SHARED_LIBRARY_PREFIX ${CMAKE_INSTALL_PREFIX})
  set(CMAKE_STATIC_LIBRARY_PREFIX ${CMAKE_INSTALL_PREFIX})
endif (WIN32)

AFAIK this is the wrong way to do it and you should be copying the libraries separately.
