### ISSUE TITLE
甚麼 should be converted to 什么, not 甚么

### ISSUE THREAD

**Issue by dddlr** [BYVoid/OpenCC#332]
甚么 is listed in [STPhrases.txt](https://github.com/BYVoid/OpenCC/blob/master/data/dictionary/STPhrases.txt) a few times, meaning that conversion from Trad -> Simp causes 甚麼 to become 甚么. (I'm not sure if this is intentional, though.)

```
干甚	幹甚
干甚么	幹甚麼
[...]
甚么	甚麼
甚么都干	甚麼都幹
[...]
葫芦里卖甚么药	葫蘆裏賣甚麼藥
葫芦里卖的甚么药	葫蘆裏賣的甚麼藥
```

Since 甚么 is very rare (and nonstandard) compared to 什么, it would make more sense to have the above cases of 甚 and 甚麼 correspond to 什 and 什么 instead.

**Comment by lotem** [comment]
I don't think it should. It's the author's choice to use a rare form of the word.
OpenCC should do nothing more than converting between the two standards: Simplified Chinese and Traditional Chinese. There's no mapping between 甚 and 什.
By the way, STPhrases.txt converts Simplified Chinese to Traditional, not the other way round.

**Comment by ddlr** [comment]
Ah, I see. I was using the [OpenCC](https://opencc.byvoid.com/) site to convert from Traditional to Simplified, which returned 甚么 for 甚麼, and since STPhrases.txt was the only place where 甚麼 was listed, I assumed that was where the Traditional -> Simplified mappings were.

I think it's safe to say that 甚麼 is considered one of the two widely used Traditional Chinese forms of 什么, even if it's a common variant of 什麼 -  with this in mind, to have 甚麼 map to 什么 would better fit the aims of OpenCC (conversion between trad and simp) in my opinion.

My understanding is that a general mapping of 甚 <--> 什 (which would be wrong) wouldn't be necessary to map 甚麼 to 什么, but I'm open to corrections if that is not the case.
