### ISSUE TITLE
Pypi packaging

### ISSUE THREAD

**Issue by BYVoid** [BYVoid/OpenCC#397]
For https://pypi.org/project/opencc-py/1.1.0/ (not ready yet).

**Comment by BYVoid** [comment]
Current error:

`CMakeLists.txt` is not packaged.

>     ERROR: Command errored out with exit status 1:
>      command: /usr/local/opt/python/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/p1/nlwy8lv96d53kdssf_rkb3sc0000gn/T/pip-install-o71v9n03/opencc-py/setup.py'"'"'; __file__='"'"'/private/var/folders/p1/nlwy8lv96d53kdssf_rkb3sc0000gn/T/pip-install-o71v9n03/opencc-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/p1/nlwy8lv96d53kdssf_rkb3sc0000gn/T/pip-install-o71v9n03/opencc-py/pip-egg-info
>          cwd: /private/var/folders/p1/nlwy8lv96d53kdssf_rkb3sc0000gn/T/pip-install-o71v9n03/opencc-py/
>     Complete output (5 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/private/var/folders/p1/nlwy8lv96d53kdssf_rkb3sc0000gn/T/pip-install-o71v9n03/opencc-py/setup.py", line 20, in <module>
>         assert os.path.isfile(_cmake_file)
>     AssertionError
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by mingruimingrui** [comment]
The opencc python package was setup to self contain `libopencc` binaries.
So packages must be pre-built then then packaged into `.whl` files before uploading to PyPi.

**Comment by mingruimingrui** [comment]
I've uploaded `opencc-py==1.0.6` to PyPi.
Which I previously tested on PyPi's testing servers.

`opencc-py==1.0.6` can now be installed on 64bit linux and macosx with the following commands
- macosx: `pip install opencc-py==1.0.6`
- linux: `pip install opencc-py==1.0.6b`

Note: I'm somehow getting file exists error for `opencc_py-1.0.6-py2.py3-none-manylinux1_x86_64.whl`. Therefore `1.0.6b`

The 2 `opencc-py==1.1.0` files are safe to remove and probably would not impact future releases.
After removal, users should then be able to download the packages with just `pip install opencc-py`.

**Comment by mingruimingrui** [comment]
Here are the files I've uploaded for reference [dist.zip](https://github.com/BYVoid/OpenCC/files/4605284/dist.zip)
sha256 20205f7eb44e827a8cc0809322b765c66d2496bb208617ca46db6623c357bed6

`.whl` files are essentially `.zip` files, so you can simply unzip them to look at their contents.

**Comment by BYVoid** [comment]
I deleted 1.1.0. You can upload again.

Do you plan to upload bdist_wheel only (no sdist)?

Is it possible to build it for Linux as well?

**Comment by mingruimingrui** [comment]
Cool! But should we keep it to 1.0.6 to follow the c++ library's version?

No `.sdist` was uploaded. I took reference from to two other common c library wrappers for python, [Numpy](https://github.com/numpy/numpy) and [pyTorch](https://github.com/pytorch/pytorch). Typically when source code needs to be compiled, the developers only uploads the built libraries. I can say with confidence that a significant portion of python developers do not have c compilers installed on their base systems, let alone cmake. Of course, if compiling from source needs to be done, I feel that it is generally a better practice to download directly from GitHub rather than PyPi.

A linux build was already uploaded to PyPi
[opencc_py-1.0.6b-py2.py3-none-manylinux1_x86_64.whl](https://files.pythonhosted.org/packages/99/43/64c5729632fbe2113a762e0fedcd4b59540f934199830f3080bb2f7372a5/opencc_py-1.0.6b-py2.py3-none-manylinux1_x86_64.whl)

**Comment by BYVoid** [comment]
You can upload it. I added you as a maintainer. Thanks.

**Comment by mingruimingrui** [comment]
Done and validated https://pypi.org/project/opencc-py

**Comment by mingruimingrui** [comment]
Testing on installed packge is has also been done for python2.7.
I guess https://github.com/BYVoid/OpenCC/issues/396 can be closed as well

**Comment by BYVoid** [comment]
Excellent.
