### ISSUE TITLE
Merge opencc and opencc-py on PyPI

### ISSUE THREAD

**Issue by BYVoid** [BYVoid/OpenCC#400]
I have contacted the original author of https://pypi.org/project/OpenCC/, and the author agreed on merging `opencc-py`.

**Comment by sgalal** [comment]
正好 PyPI 上的 OpenCC 可以和 OpenCC 程序用同樣的版本號了

**Comment by BYVoid** [comment]
@mingruimingrui Can you please let me know how generate and upload bdist?

Like: opencc_py-1.1.0-py2.py3-none-manylinux1_x86_64.whl and opencc_py-1.1.0-py2.py3-none-macosx_10_9_x86_64.whl

**Comment by mingruimingrui** [comment]
I'm actually preparing a few scripts to do just that because there's a list of things to take note of.

1. PyPi should ship compiled packages [1]
2. Complied packages are to be stored in zip files ending with the ext '.whl' [2]
3. Packages are to be tagged based on the platform, package version and python version compatibility
  - Should follow the structure `<PkgNameAndVer>-<PyVer>-<AbiTag>-<PlatName>.whl`
  - Platform name should be `manylinux1_` for 64bit linux

[1] That way users would not need to go through the hassle of installing compilers and building binaries.
[2] As recommended in PEP427 and PEP527

**Comment by mingruimingrui** [comment]
With that said, here are the binaries for OpenCC-1.1.0.
[dist.zip](https://github.com/BYVoid/OpenCC/files/4622200/dist.zip)
sha256 e2fa1bddfd028431476fec432691fe94cd04629fd2be85b77d2910cae017c147

**Comment by mingruimingrui** [comment]
I was working on this other branch
https://github.com/mingruimingrui/OpenCC/tree/feature/pybind11

The good part of that branch is that `python setup.py bdist_wheel` would automatically select the correct python version and platform name. This makes packaging `.whl` files much more straight forward.

As for why `pybind` was used, it's so that the C library throws an error when an invalid configFileName is provided.

**Comment by mingruimingrui** [comment]
Let me make a PR for this issue

**Comment by BYVoid** [comment]
After a few changes, I built it on Windows.

https://pypi.org/manage/project/OpenCC/release/1.1.0.post1/
